# -*- coding: utf-8 -*-
import time

def test_spb_form(app):
    app.open_home_page()
    app.dispatch.fill_dest_country("АЗЕРБАЙДЖАН")
    app.dispatch.fill_posting_type("Послыка")
    app.go_to_second_form()
    # FORM 2
    app.sender.fill_company_name("ООО Компания")
    app.sender.fill_zipcode("111394")
    app.sender.fill_region()
    app.sender.fill_street("Полимерная ул.")
    # app.sender.fill_city()
    app.sender.fill_home("5")
    app.sender.fill_inn("773605000312")
    app.sender.fill_kpp("997250001")
    app.reciver.fill_resiv_name("ИВАНОВ ИВАН ИВАНОВИЧ")
    app.reciver.fill_resiv_city("Сочи")
    app.reciver.fill_resiv_street("Пляжная")
    app.reciver.fill_resiv_home("8")
    app.go_to_third_form()
    # FORM 3
    app.blank.fill_attachs()
    app.blank.fill_requisities("1")
    app.blank.fill_phone("1")
    app.blank.fill_fax("1")
    app.blank.fill_email("emial@gmail.com")
    app.blank.fill_licence("1")
    app.blank.fill_licence2("1")
    app.blank.fill_cert("1")
    app.blank.fill_cert2("1")
    app.blank.fill_invoice("1")
    app.blank.fill_invoice2("1")
    app.blank.fill_declaired_value("1")
    app.blank.fill_cash_on_delivery("1")
    # app.blank.fill_currancy("RUB, Российский рубль")
    app.blank.fill_parse_number("12")
    app.blank.fill_cur_post_number("12")
    app.blank.fill_note("примечани")
    app.blank.fill_period("30")
    app.form_blank()
